apiVersion: v1
kind: ConfigMap
metadata:
 name: jona27081-config
 labels:
   app: postgres
data:
 PROD_SECRET_KEY: 'dema_27'
 PROD_DATABASE: 'foriagqo'
 PROD_USER: 'foriagqo'
 PROD_PASSWORD: 'td6kk3KOcz9MtWd9grPk-goL2hAJY980'
 PROD_HOST: 'raja.db.elephantsql.com'
 PROD_PORT: "5432"
